# NexT theme configuration.
# See: https://theme-next.js.org/docs/getting-started/configuration

custom_file_path:
  head: source/_data/head.njk

scheme: Gemini
darkmode: true

menu:
  home: / || fa fa-home
  archives: /archives/ || fa fa-archive || 归档

social:
  GitHub: https://github.com/Sunshine0912-love || fab fa-github

codeblock:
  theme:
    light: github
    dark: github-dark
  prism:
    light: prism
    dark: prism-dark
  copy_button:
    enable: true
    style: mac
  language: true

mermaid:
  enable: true
  theme:
    light: default
    dark: dark

math:
  every_page: false
  mathjax:
    enable: false
    tags: none
  katex:
    enable: false

creative_commons:
  license: by-nc-sa
  size: small
  sidebar: false
  post: true

footer:
  since: 2026
  powered: true
